spring:
  config:
    activate:
      on-profile: test

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create